name       : perl-gtk2-notify
version    : 0.05
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/F/FL/FLORA/Gtk2-Notify-0.05.tar.gz : 88189ae68dfbd54615ad133df07e2ec8048d06d8b9586add1227d74eb2ebb047
license    : LGPL-2.0
component  : programming.perl
summary    : Perl interface to libnotify.
description: |
    Gtk2::Notify - Perl interface to libnotify.
builddeps  :
    - pkgconfig(libnotify)
    - pkgconfig(gtk+-2.0)
    - perl-cairo
    - perl-extutils-depends
    - perl-extutils-pkgconfig
    - perl-glib
    - perl-gtk2
    - perl-pango
rundeps    :
    - perl-gtk2
setup      : |
    %patch -Np2 < $pkgfiles/libnotify.patch
    sed -i "s/use lib 'ext';/use lib 'ext';\ruse lib '.';/g" Makefile.PL
    sed -i "s/notify_notification_new (class, summary, body=NULL, icon=NULL, attach=NULL)/notify_notification_new (class, summary, body=NULL, icon=NULL)/g" xs/Notify.xs
    sed -i "s/summary, body, icon, attach/summary, body, icon/g" xs/Notify.xs
    sed -i "s/GtkWidget_ornull \*attach//g" xs/Notify.xs
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
